// JiraConnection.idl : IDL source for JiraConnection
//

// This file will be processed by the MIDL tool to
// produce the type library (JiraConnection.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";
import "..\model-libs\objmdl\objmdl_contract_i.idl";
import "jiraconnection_contract_i.idl";
import "..\model-libs\netmdl\netmdl_contract_i.idl";

[
	uuid(ACAA2068-47E3-4B71-B6E6-1AC842A6DB6A),
	version(1.0),
]

library JiraConnectionLib
{
	importlib("stdole2.tlb");
	[
		uuid(F80D4532-3ECE-407F-9712-897BC577E930)
	]
	coclass JiraObject
	{
		[default] interface IJiraObject;
		interface IPersistStream;
		interface IVariantObject;
	};

	[
		uuid(FCDE7B47-0B37-455D-BA59-C088C5E1A60F)		
	]
	coclass JiraObjectsCollection
	{
		[default] interface IJiraObjectsCollection;
		interface IObjArray;
		interface IPersistStorage;
	};

	[
		uuid(CAD49B0E-E18C-4855-93A8-AE3FF65FF0D3)		
	]
	coclass JiraConnection
	{
		[default] interface IJiraConnection;
		interface ISupportErrorInfo;
		interface IErrorInfo;
	};
	[
		uuid(6EA78630-DC6D-4D2B-91F0-686B260F29D6)
	]
	coclass PluginTable
	{
		[default] interface IPluginTable;
	};
};

import "shobjidl.idl";
