import "oaidl.idl";
import "ocidl.idl";
import "..\model-libs\objmdl\objmdl_contract_i.idl";
import "..\model-libs\viewmdl\viewmdl_contract_i.idl";
import "..\JiraConnection\JiraConnection_contract_i.idl";
import "..\NotifierHost\NotifierHost_contract_i.idl";

[
    uuid(1B23E426-1C4C-49EE-949C-B94DBDB0C333),
    version(1.0),
]
library JiraNotifyLib
{
    importlib("stdole2.tlb");
    [
		uuid(11F756D4-7BD4-4A51-B9F1-297362E08C1A)
	]
	coclass SettingsControl
	{
		[default] interface IControl;
	};
};